### importing the libraries

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
dataset= pd.read_csv("dataset.csv")
dataset.head()

Country   Age    Salary Purchased
0   France  44.0  72000.00        No
1    Spain  27.0  48000.00       Yes
2  Germany  30.0  54000.00       No 
3    Spain  38.0  61000.00        No
4  Germany  40.0  63777.77       Yes

## Importing the dataset

In [36]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,3].values
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77]
 ['France' 35.0 58000.0]
 ['Spain' 38.77 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 87000.0]]


In [37]:
print(y)

['No' 'Yes' 'No ' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## taking care of missing values

In [38]:
from sklearn.preprocessing import Imputer


In [39]:
imputer=Imputer(missing_values='NaN', strategy='mean', axis=0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

C:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


## Importing LabelEncoder, Onehotencoder for categorical data

In [40]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])
onehotencoder=OneHotEncoder(categorical_features=[0])
X=onehotencoder.fit_transform(X).toarray()
labelencoder_y=LabelEncoder()
y=labelencoder_X.fit_transform(y)

C:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


### Splitting dataset into training and testing

In [41]:
from sklearn.model_selection import train_test_split

In [43]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)

In [53]:
print(X_train)

[[0.000000e+00 1.000000e+00 0.000000e+00 4.000000e+01 6.377777e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 3.700000e+01 8.700000e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 2.700000e+01 4.800000e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 3.877000e+01 5.200000e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 4.800000e+01 7.900000e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 3.800000e+01 6.100000e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 4.400000e+01 7.200000e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 3.500000e+01 5.800000e+04]]


### Feature Scaling

In [54]:
from sklearn.preprocessing import StandardScaler

In [57]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)
